// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // return linux;
      // Uncomment the following lines if you want to support Linux
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEqxbXDvjoYZLP1Ja2VFj7EFulMR1tkE',
    appId: '1:312607240262:web:8f81709adc848df5cf5a47',
    messagingSenderId: '312607240262',
    projectId: 'arandomtestproject',
    authDomain: 'arandomtestproject.firebaseapp.com',
    storageBucket: 'arandomtestproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHszwS_tUhz0mRHw4cmA51i9czurCiUk',
    appId: '1:312607240262:android:c00d42d0cf942885cf5a47',
    messagingSenderId: '312607240262',
    projectId: 'arandomtestproject',
    storageBucket: 'arandomtestproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOYBftU6-01Xpi4s4BRHj8eyMsSBcxGi4',
    appId: '1:312607240262:ios:e8ffa8d28b7f6479cf5a47',
    messagingSenderId: '312607240262',
    projectId: 'arandomtestproject',
    storageBucket: 'arandomtestproject.firebasestorage.app',
    iosBundleId: 'com.example.homecare0x1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOYBftU6-01Xpi4s4BRHj8eyMsSBcxGi4',
    appId: '1:312607240262:ios:e8ffa8d28b7f6479cf5a47',
    messagingSenderId: '312607240262',
    projectId: 'arandomtestproject',
    storageBucket: 'arandomtestproject.firebasestorage.app',
    iosBundleId: 'com.example.homecare0x1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjEqxbXDvjoYZLP1Ja2VFj7EFulMR1tkE',
    appId: '1:312607240262:web:8422d2924b39a15bcf5a47',
    messagingSenderId: '312607240262',
    projectId: 'arandomtestproject',
    authDomain: 'arandomtestproject.firebaseapp.com',
    storageBucket: 'arandomtestproject.firebasestorage.app',
  );

}